### ISSUE TITLE
Cannot build on Node v6.5.0

### ISSUE THREAD

**Issue by dislick** [AsamK/JodelJS#1]
Hey, I'm having trouble building this app using Node v6.5.0 and v5.2.0.

`cp src/app/settings.js.sample src/app/settings.js`
`npm run build`
```
> JodelJS@ build /Users/asdf/repos/JodelJS
> mkdir -p build && cp -r img build/ && cp src/index.htm build/ && npm run build-css & npm run build-js


> JodelJS@ build-css /Users/asdf/repos/JodelJS
> lessc --clean-css="--s1 --advanced" --npm-import --autoprefix="> 0.5%" style/main.less build/main.css


> JodelJS@ build-js /Users/asdf/repos/JodelJS
> NODE_ENV=production browserify src/app/main.js | uglifyjs -cm > build/main.js

SyntaxError: /Users/asdf/repos/JodelJS/src/views/AddPost.js: Only one default export allowed per module.
  110 | AddPost = connect(mapStateToProps)(AddPost);
  111 | 
> 112 | export default AddPost
      | ^
  113 | 
    at File.buildCodeFrameError (/Users/asdf/repos/JodelJS/node_modules/babel-core/lib/transformation/file/index.js:431:15)
    at NodePath.buildCodeFrameError (/Users/asdf/repos/JodelJS/node_modules/babel-traverse/lib/path/index.js:140:26)
    at PluginPass.exit (/Users/asdf/repos/JodelJS/node_modules/babel-plugin-transform-es2015-modules-commonjs/lib/index.js:253:29)
    at newFn (/Users/asdf/repos/JodelJS/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/Users/asdf/repos/JodelJS/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/asdf/repos/JodelJS/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/asdf/repos/JodelJS/node_modules/babel-traverse/lib/path/context.js:117:8)
    at TraversalContext.visitQueue (/Users/asdf/repos/JodelJS/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/Users/asdf/repos/JodelJS/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/Users/asdf/repos/JodelJS/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/Users/asdf/repos/JodelJS/node_modules/babel-traverse/lib/index.js:114:17)
```

**Comment by dislick** [comment]
I was able to fix the build by removing the redundant `default` export:
````diff
 import classnames from "classnames";
 import ColorPicker from "./ColorPicker";
 
-export default class AddPost extends PureComponent {
+export class AddPost extends PureComponent {
     constructor(props) {
         super(props);
         const messageDraft = sessionStorage.getItem("messageDraft");
```

But as soon as I copy the `build/` directory to a webserver and open `index.htm` this JavaScript error appears:
````
main.js:24 Uncaught TypeError: Cannot read property 'map' of undefined
````

**Comment by dislick** [comment]
Looks like the 
![image](https://cloud.githubusercontent.com/assets/3121902/18196623/b054ee5c-70f2-11e6-92a6-f958d4377788.png)

**Comment by AsamK** [comment]
Interesting, my build doesn't complain about the duplicate default, (also node v6.5.0)
I had fixed the map error already locally, but not pushed yet. It should work now.
